#!/bin/ksh
#################################################
# job settings
#################################################
INIT_D=init_d_bldsva
INIT_M=init_m_bldsva
INIT_Y=init_y_bldsva
INIT_H=init_h_bldsva
CONV_SCHEME=3
#
username_cluma=pshrestha
username_sx9=xxxx
nsteps=nstop_cos_bldsva
#

lmworkdir_cluma=__rundir__
lmoutdir_cluma=__rundir__/cosmo_out
lmrestdir_cluma=__rundir__/cosmo_rest
lmindir_cluma=__forcingdir__/

#
lmworkdir_sx9=/e/uhome/xxxx/cosmo/
lmoutdir_sx9=/e/gtmp/xxxx/cosmo/
lmindir_sx9=/e/uscratch/xxxx/cosmo/
#
#################################################
# host detection
#################################################
cmd=$1
if [[ $1 = clean ]]; then
  if [[ ($HOST = lxe00) || ($HOST = lxe01) ]]; then
    cmd=cleansx9
    echo "... assuming sx9 as host"
  fi
  if [[ $HOST = m01 ]]; then
    cmd=cleancluma
    echo "... assuming cluma as host"
  fi
fi
#
if [[ $1 = exe ]]; then
  if [[ ($HOST = lxe00) || ($HOST = lxe01) ]]; then
    cmd=exesx9
    echo "... assuming sx9 as host"
  fi
  if [[ $HOST = m01 ]]; then
    cmd=execluma
    echo "... assuming cluma as host"
  fi
fi
#################################################
# host-depending settings
#################################################
#
nprocspernode=999
if [[ $cmd = execluma ]]; then
  nprocspernode=4; queue=batch; username=$username_cluma
  lmworkdir=$lmworkdir_cluma; lmoutdir=$lmoutdir_cluma; lmindir=$lmindir_cluma ; lmrestdir=$lmrestdir_cluma
  echo "###### JOB RUN ON CLUMA ######"
elif [[ $cmd = exesx9 ]]; then
  nprocspernode=16; queue=normal@sx9esiox1; username=$username_sx9
  lmworkdir=$lmworkdir_sx9; lmoutdir=$lmoutdir_sx9; lmindir=$lmindir_sx9
  echo "###### JOB RUN ON SX9 ######"
elif [[ $cmd = cleancluma ]]; then
  nprocspernode=999; queue=none
  lmworkdir=$lmworkdir_cluma; lmoutdir=$lmoutdir_cluma; lmindir=$lmindir_cluma ; lmrestdir=$lmrestdir_cluma
  echo "LMRUN_UC: clean up"
elif [[ $cmd = cleansx9 ]]; then
  nprocspernode=999; queue=none
  lmworkdir=$lmworkdir_sx9; lmoutdir=$lmoutdir_sx9; lmindir=$lmindir_sx9
  echo "LMRUN_UC: clean up"
fi
#
#################################################
# number of processors
#################################################
#
NPX=1
NPY=1
if [[ $cmd = exesx9 ]]; then
  # ON SX9 keep NPX=1 for performance reasons
  NPX=1
  NPY=$nprocspernode
fi
if [[ $cmd = execluma ]]; then
  # ON CLUMA arbitrary settings possible
  NPX=nprocx_cos_bldsva
  NPY=nprocy_cos_bldsva
fi
NPIO=0
NP1=`expr $NPX \* $NPY`; NP=`expr $NP1 + $NPIO`; N1=`expr $NP + $nprocspernode - 1`; NODES=`expr $N1 \/ $nprocspernode`
init_date=${INIT_Y}${INIT_M}${INIT_D}
#
#################################################
# define directories
#################################################
#
jobname=cosmo${INIT_D}${INIT_M}${INIT_Y}
runname=cosmo4.21agb_${INIT_D}.${INIT_M}.${INIT_Y}.${INIT_H}00_v03/
workdir=$lmworkdir/
INIDIR=$lmindir
OUTPUT=$lmoutdir
DATUM=${INIT_Y}${INIT_M}${INIT_D}${INIT_H}
RESTAR=$lmrestdir
BD_DIR=$INIDIR
#
#################################################
# selection of actions
#################################################
#
#################################################
# display help
#################################################
#
if [[ ($cmd != execluma) && ($cmd != exesx9) && ($cmd != cleancluma) && ($cmd != cleansx9) ]]; then
  umacho
  echo "COSMORUN : Runs COSMO, cleans working and output directories (on automatically detected host)."
  echo
  echo "SYNTAX :"
  echo
  echo "lmrun_uc clean                  cleans working and output directories"
  echo
  echo "lmrun_uc exe                    starts COSMO"
  echo
  echo "lmrun_uc cleancluma, execluma   explicitly sets cluma as host"
  echo
  echo "lmrun_uc cleansx9, exesx9       explicitly sets sx9 as host"
  echo
  echo "lmrun_uc                        displays help text"
  echo
  exit
fi
#
#################################################
# generate output directory
#################################################
#
if [ ! -d $OUTPUT ] ; then
  mkdir -p $OUTPUT
fi
if [ ! -d $RESTAR ] ; then
  mkdir -p $RESTAR
fi

#
echo "VK CONFIG with DATE        ${INIT_D}.${INIT_M}.${INIT_Y} ${INIT_H}:00"
echo "VK CONFIG with CONV.SCHEME $CONV_SCHEME"
echo "VK CONFIG with INPUTDIR    $INIDIR"
echo "VK CONFIG with WORKDIR     $workdir"
echo "VK CONFIG with OUTPUTDIR   $OUTPUT"
echo "VK CONFIG with JOBNAME     $jobname"
#
#################################################
# clean up only
#################################################
#
if [[ ($cmd = cleancluma) || ($cmd = cleansx9) ]]; then
  echo "tidy up ..."
  cd $workdir
  rm -f cosmo_de_job
  rm ftrace.out.*
  rm mon.out.*
  rm -f *~
  rm -f YU*
  rm -f INPUT_*
  rm -f ${jobname}*
  rm -f output/*
  rm -f $OUTPUT/*
  rm -f cosmo_de_job
  rm -f M_*
  rm -f diag*
  exit 0
fi
#
#################################################
# start COSMO
#################################################
#
if [[ ($cmd = execluma) || ($cmd = exesx9) ]]; then
rm -f cosmo_de_job
echo "generate cosmo_de_job ..."

cat >> cosmo_de_job << namelists
#################################################
# namelist settings
#################################################

#################################################
# cat together the INPUT*-files
#################################################

cat > INPUT_ORG << end_input_org
 &LMGRID
  startlat_tot=-1.75,   startlon_tot  =  -1.5,
  pollat=39.0,   pollon=-173.0,
  dlon=0.010,   dlat=0.010,
  ie_tot=ie_tot_bldsva,   je_tot=je_tot_bldsva,   ke_tot=80,
 /
 &RUNCTL
  dt=dt_cos_bldsva,
  hstart = __hstart__,   nstop = $nsteps,
  ydate_ini='$DATUM',
  itype_timing=0,
  ncomm_type=3,
  lreproduce    = .TRUE.,  
  luseobs       = .FALSE., 
  lphys         = .TRUE.,
  ldiagnos      = .TRUE.,
  luse_rttov    = .FALSE.,
  leps          = .FALSE.,
  lreorder      = .FALSE.,
  ldatatypes    = .TRUE., 
  ltime_barrier = .TRUE.,
  lartif_data   = .FALSE., 
    lperi_x     = .FALSE.,
    lperi_y     = .FALSE.,
  nprocx = $NPX,  nprocy = $NPY,   nprocio = $NPIO,
  nboundlines=nbdl_cos_bldsva, 
  ldump_ascii=.TRUE., 
  idbg_level=20,
 /
 &TUNING
  rlam_mom  =   0.0,
  rlam_heat =   1.0,
  rat_sea   =  20.0,
  rat_lam   =   1.0,
  rat_can   =   1.0, 
  wichfakt  =   0.0,
  c_lnd     =   2.0,
  c_soil    =   1.0,
  c_sea     =   1.5,
  pat_len   = 500.0,
  tur_len   = 150.0,
  z0m_dia   =   0.2,
  crsmin    = 150.0,
  clc_diag  =   0.5,
  qc0       =   0.0002,
  q_crit    =   1.6,
  mu_rain   =   0.5,
  rain_n0_factor = 0.1,
  v0snow    =    20,
  tkhmin    =   0.4,
  tkmmin    =   0.4,
 /
end_input_org

cat > INPUT_IO  << end_input_io
 &IOCTL
  lasync_io=.FALSE, 
  ngribout=1,
  ydir_restart_out='$RESTAR',
  ydir_restart_in='$INIDIR',
  nhour_restart=__nhour_restart_start__,__nhour_restart_stop__,__nhour_restart_incr__,
  ytunit_restart='f',
!  yform_read='grb1',
 /
 &DATABASE
 /
 &GRIBIN
  lbdana=.FALSE.,
  ydirini='$INIDIR',
  lchkini=.TRUE.,
  ydirbd='$BD_DIR',
  lchkbd=.TRUE.,
  hincbound=1.0,
  lana_qi    = .TRUE.,  llb_qi    = .TRUE., 
  lana_qg    = .FALSE.,  llb_qg    = .FALSE.,
  lana_qr_qs = .TRUE.,  llb_qr_qs = .TRUE.,
  lana_rho_snow=.FALSE., 
  lan_w_so=.TRUE.,
  lan_hmo3=.TRUE.,  lan_plcov=.TRUE., lan_lai=.TRUE.,  lan_rootdp=.TRUE.,
  lan_t_so0=.TRUE., lan_t_cl=.TRUE.,  lan_w_cl=.TRUE., lan_vio3=.TRUE.,
  lan_t_snow=.TRUE.,lan_w_i=.TRUE.,   lan_w_snow=.TRUE., lan_rho_snow=.TRUE.,
 /
 &GRIBOUT
  lanalysis=.FALSE.,
  luvmasspoint=.true.,
  lcheck=.TRUE.,
  lwrite_const=.TRUE.,
  l_fi_filter=.TRUE.,
    ncomb=__ncomb_start__,$nsteps,__dump_cos_interval__,
!  ncomb=__ncomb_start__,$nsteps,50,
!  ncomb=14400,20400,50
  nunit_of_time=1,
  yform_write='ncdf',
  ydir='$OUTPUT',
  yvarml='U         ','V         ','W         ','T         ',
         'P         ','QV        ','QC        ','QI        ',
         'QR        ','QS        ','QG        ','QH        ',
         'NCCLOUD   ','NCICE     ','NCRAIN    ','NCSNOW    ',
         'NCGRAUPEL ','NCHAIL    ','REFF_C    ','REFF_I    ',
         'RAIN_GSP  ','SNOW_GSP  ','RAIN_CON  ','SNOW_CON  ',
         'TOT_PREC  ','HAIL_GSP  ',
         'T_G       ','QV_S      ','PS        ',
         'ASOB_S    ','ATHB_S    ','ASHFL_S   ','ALHFL_S   ',
         'AUMFL_S   ','AVMFL_S   '
 /
end_input_io

cat > INPUT_DYN << end_input_dyn
 &DYNCTL
  lspubc=.TRUE.,
  nrdtau=5, 
  xkd=0.1,
  rlwidth=20000.0, 
  lcond=.TRUE., 
  lhordiff=.true.,
    itype_hdiff=2, 
    l_diff_Smag=.TRUE., 
    hd_dhmax=250.,
    hd_corr_trcr_bd=0.0, 
    hd_corr_t_bd=0.75, 
    hd_corr_u_bd=0.75, 
    hd_corr_p_bd=0.75,
    hd_corr_trcr_in=0.0, 
    hd_corr_t_in=0.0,  
    hd_corr_u_in=0.1,  
    hd_corr_p_in=0.0,
  l2tls=.TRUE., 
    irunge_kutta=1,
      irk_order=3,
      iadv_order=5,
      itype_fast_waves=2,
    y_scalar_advect='BOTT2_STRANG',
  ldyn_bbc=.FALSE., 
    itype_bbc_w=114,
  ldiabf_lh=.TRUE.,
  itype_outflow_qrsg=2,
 /
end_input_dyn

cat > INPUT_PHY << end_input_phy
 &PHYCTL
    lgsp=.TRUE.,
      itype_gscp=2473,
      lsuper_coolw=.TRUE.,
    lrad=.TRUE.,
      nradcoarse=1,
      lradf_avg=.FALSE.
      hincrad=0.25,
      lforest=.TRUE.,
      itype_albedo=1,
    ltur=.TRUE.,
      ninctura=1,
      lexpcor=.FALSE.,
      ltmpcor=.FALSE.,
      lprfcor=.FALSE.,
      lnonloc=.FALSE.,
      lcpfluc=.FALSE.,
      limpltkediff=.TRUE.,
      itype_turb=3,
      imode_turb=1,
      itype_tran=2,
      imode_tran=1,
      itype_wcld=2,
      icldm_rad =4,
      icldm_turb=2,
      icldm_tran=0,
      itype_synd=2,
    lsoil=.TRUE.,
      itype_evsl=2,
      itype_trvg=2,
      lmulti_layer=.TRUE.,
      lmelt=.TRUE.,
      lmelt_var=.TRUE.,
      ke_soil = 7,
      czml_soil = 0.005, 0.02, 0.06, 0.18, 0.54, 1.62, 4.86, 14.58,
    lconv=.TRUE.,
      lcape=.FALSE.,
      lconf_avg=.TRUE.,
      lconv_inst=.TRUE.,
      itype_conv=3,
      nincconv=10,
    llake=.FALSE.,
    lseaice=.FALSE.,
    lsso=.FALSE.,
      ltkesso=.FALSE.,
 /
end_input_phy

cat > INPUT_DIA << end_input_dia
 &DIACTL
  itype_diag_gusts=4,
  n0meanval=0, nincmeanval=1,
  lgplong=.TRUE., lgpshort=.FALSE., lgpspec=.FALSE.,
  n0gp=0,      hincgp=0.25,
  stationlist_tot= 0, 0, 50.730,  7.071, 'Bonn_Radar',
 /
end_input_dia

cat > INPUT_IDEAL << end_input_artifctl
 &ARTIFCTL
 ldebug_artif = .true.,
  idbg_artif_level = 5,
 irefatm = 2,
  p0sl = 1e5,       ! reference surface (z = 0.0 m) pressure [Pa]
  t0sl = 300.0,     ! reference surface temperature [K]
  dt0lp = 42.0,     ! logarithmic temperature gradient [K]
  delta_t = 75.0,   ! temperature diff. surface - stratosphere [K]
  h_scal = 10000.0, ! e-folding height of exponential adjustment to the stratosphere temp. [m]
  bvref = 0.01,     ! constant Brund-Vaisala-frequency for irefatm=3 [1/s]
 ivctype = 2,
  zspacing_type = 'predefined',! sub-type of coordinate spec.
  vcflat = 11000.0,         ! height, above which coordinate levels become flat [m]
 linit_realoro = .false.,
  href_oro=140.0,
  itype_topo = 0, 
  lhill = .false., .false., .false.,
 itype_soil_c = 1, 
  z0_c      = 0.01,        ! z_0 in m
  fr_land_c = 1.0,         ! land fraction, dimensionless
  soiltyp_c = 6.0,         ! clay loam soiltype, dimensionless
  plcov_c   = 0.2,         ! plant cover, dimensionless
  lai_c     = 0.9,         ! LAI, dimensionless
  rootdp_c  = 0.6,         ! root depth in m
  for_e_c   = 0.0,         ! area fraction of evergreen forests
  for_d_c   = 0.0,         ! area fraction of decidious forests
  h_ice_c   = 0.1,         ! ice thickness in m
 itype_soil_tw = 1, 
  t_surf_c  = -1.0,     ! baseline t_s (if < 0, the atmosphere temperature at the surface is used)
  t_soil_c  = 287.0,   ! t_soil in K (if < 0, t_s is taken instead) for all soiltypes except glaciers)
  wf_soil_c = 0.3,      ! soil water saturation, dimensionless (0 ... 1)
  t_snow_c  = -1.0,     ! t_snow in K (if < 0, t_s is taken instead)
  w_snow_c  = 0.0,      ! snow water equivalent in m H2O
  w_i_c     = 0.0,      ! interception storage on plants in m H2O
  t_ice_c   = -1.0,     ! T at the snow-ice or air-ice interf. in K (if < 0, t_s is taken instead) 
  t_water_c = -1.0,     ! T at the water-ice or water-air interface in K (if < 0, t_s is taken instead)
 itype_artifprofiles = 1, 
 rasofile = '$rasoinput',
 ! itype_anaprof_tqv = 2, 
  !itype_anaprof_uv = 3,
  !  nlayers_poly = 6,
  !  p_base_poly = 1e5,
  !  h_poly    =    0.0,300.  ,1500.0,5000.0,10000  ,13000.0,
  !  t_poly    = 299.9,299.9 , 299.9,276.5 , 243.5 , 219.5,
  !  tgr_poly  =  0.00,0.000 , 0.0052,0.0066,0.008 , -0.0007,
  !  rh_poly   =  0.656,0.356 , 0.356,0.321 ,0.321  , 0.021,
  !  rhgr_poly =  0.001,0.000 ,1.0E-5,0.000 ,1.0E-4 , 0.0, 
   ! u_infty   = 0.5,
 linitw_followeta = .true.,
 lnosurffluxes_m = .false.,
 lnosurffluxes_h = .false.,
 ltempdist = .false., .false., .false.,.false.,
/
end_input_artifctl

namelists

#################################################
# cleanup
#################################################

rm -f INPUT_ORG INPUT_IO INPUT_DYN INPUT_DIA INPUT_PHY INPUT_INI
rm -f INPUT_ASS INPUT_SAT INPUT_EPS

chmod u+x cosmo_de_job
fi
./cosmo_de_job
exit 0
