#!/bin/tcsh
#2015-04-30_KGo
#USAGE="source $0"
#for bld and work w/ TerrSysMP on JUROPATEST/JURECA
#for standard user

module purge


# Only necessary if modules are missing after maintenence
module use /usr/local/software/jureca/OtherStages
module load Stages/2015b 


# basic toolchain, latest Intel compilers and ParaStation MPI
module load intel-para/2015.07

# software development
#module load git/2.3.2

# libs for TerrSysMP
module load Tcl/8.6.3
module load Hypre/2.10.0b
module load Silo/4.9.1
#grib1 dwd
module load netCDF/4.3.2
module load netCDF-Fortran/4.4.2
module load parallel-netcdf

module load Scalasca/2.2.1

# standard analysis and vis. libs and tools 
#module load NCO/4.4.8
#module load CDO/1.6.8
#module load ncview/2.1.5
#module load Python/2.7.9 
#matplotlib/1.3.1-Python-2.7.9
#netCDF4-python/1.1.7.1-Python-2.7.9 
####ScientificPython/2.9.4-Python-2.7.9 
#basemap
#NCL
#image magick / feh ... some standard viewer is missing

module li
