#!/bin/tcsh
#2020_04_08
#USAGE="source $0"
#for bld and work w/ TerrSysMP on SUPERMUC
#for standard user

# Only necessary if modules are missing after maintenence
#
# standard modules on Juwels

# Only necessary if modules are missing after maintenence
#module load gcc/9
module load intel/19.0
#module load intel/2020 
module load mpi.intel/2019
#module load intel/2020_gcc
#module load scalasca/2.4

# libs for TerrSysMP ###These are still needed!
#module load Tcl/.8.6.8
#module load Hypre/2.14.0
#module load Silo/4.10.2
#grib1 dwd

module load hdf5/1.10.2-intel-impi-frt-threadsafe
module load netcdf/4.6.1-intel-impi-hdf5v1.10-parallel
module load netcdf-fortran/4.4.4-intel-impi-hdf5v1.10
module load parallel-netcdf/1.8.1-intel-impi
#module load hdf5/1.10.2-intel-impi-frt-threadsafe
#module load netcdf-fortran/4.4.4-intel-impi-hdf5v1.10
#module load netcdf/4.6.1-intel-impi-hdf5v1.10-parallel
#module load parallel-netcdf/1.8.1-intel-impi


# standard analysis and vis. libs and tools 
module load nco/4.6.7
module load qt/5.7
module load openblas/0.3.2
#module load NCL/6.5.0
#module load CDO/1.9.3
module load ncview/2.1.7-impi
module load python/3.6_intel
#module load matplotlib/1.3.1-Python-2.7.9
#module load netcdf4-python/1.4.2-Python-3.6.6
#module load basemap/1.0.7-Python-2.7.14
#module load petsc4py/3.9.0-Python-3.6.5
#image magick / feh ... some standard viewer is missing

module li
