#!/bin/ksh
#################################################
# job settings
#################################################
INIT_D=init_d_bldsva
INIT_M=init_m_bldsva
INIT_Y=init_y_bldsva
INIT_H=init_h_bldsva
CONV_SCHEME=3
#
username_cluma=pshrestha
username_sx9=xxxx
nsteps=nstop_cos_bldsva
#

lmworkdir_cluma=__rundir__
lmoutdir_cluma=__rundir__/cosmo_out
lmindir_cluma=__forcingdir__/

#
lmworkdir_sx9=/e/uhome/xxxx/cosmo/
lmoutdir_sx9=/e/gtmp/xxxx/cosmo/
lmindir_sx9=/e/uscratch/xxxx/cosmo/
#
#################################################
# host detection
#################################################
cmd=$1
if [[ $1 = clean ]]; then
  if [[ ($HOST = lxe00) || ($HOST = lxe01) ]]; then
    cmd=cleansx9
    echo "... assuming sx9 as host"
  fi
  if [[ $HOST = m01 ]]; then
    cmd=cleancluma
    echo "... assuming cluma as host"
  fi
fi
#
if [[ $1 = exe ]]; then
  if [[ ($HOST = lxe00) || ($HOST = lxe01) ]]; then
    cmd=exesx9
    echo "... assuming sx9 as host"
  fi
  if [[ $HOST = m01 ]]; then
    cmd=execluma
    echo "... assuming cluma as host"
  fi
fi
#################################################
# host-depending settings
#################################################
#
nprocspernode=999
if [[ $cmd = execluma ]]; then
  nprocspernode=4; queue=batch; username=$username_cluma
  lmworkdir=$lmworkdir_cluma; lmoutdir=$lmoutdir_cluma; lmindir=$lmindir_cluma
  echo "###### JOB RUN ON CLUMA ######"
elif [[ $cmd = exesx9 ]]; then
  nprocspernode=16; queue=normal@sx9esiox1; username=$username_sx9
  lmworkdir=$lmworkdir_sx9; lmoutdir=$lmoutdir_sx9; lmindir=$lmindir_sx9
  echo "###### JOB RUN ON SX9 ######"
elif [[ $cmd = cleancluma ]]; then
  nprocspernode=999; queue=none
  lmworkdir=$lmworkdir_cluma; lmoutdir=$lmoutdir_cluma; lmindir=$lmindir_cluma
  echo "LMRUN_UC: clean up"
elif [[ $cmd = cleansx9 ]]; then
  nprocspernode=999; queue=none
  lmworkdir=$lmworkdir_sx9; lmoutdir=$lmoutdir_sx9; lmindir=$lmindir_sx9
  echo "LMRUN_UC: clean up"
fi
#
#################################################
# number of processors
#################################################
#
NPX=1
NPY=1
if [[ $cmd = exesx9 ]]; then
  # ON SX9 keep NPX=1 for performance reasons
  NPX=1
  NPY=$nprocspernode
fi
if [[ $cmd = execluma ]]; then
  # ON CLUMA arbitrary settings possible
  NPX=nprocx_cos_bldsva
  NPY=nprocy_cos_bldsva
fi
NPIO=0
NP1=`expr $NPX \* $NPY`; NP=`expr $NP1 + $NPIO`; N1=`expr $NP + $nprocspernode - 1`; NODES=`expr $N1 \/ $nprocspernode`
init_date=${INIT_Y}${INIT_M}${INIT_D}
#
#################################################
# define directories
#################################################
#
jobname=cosmo${INIT_D}${INIT_M}${INIT_Y}
runname=cosmo4.21agb_${INIT_D}.${INIT_M}.${INIT_Y}.${INIT_H}00_v03/
workdir=$lmworkdir/
INIDIR=$lmindir
OUTPUT=$lmoutdir
DATUM=${INIT_Y}${INIT_M}${INIT_D}${INIT_H}
RESTAR=$INIDIR
BD_DIR=$INIDIR
#
#################################################
# selection of actions
#################################################
#
#################################################
# display help
#################################################
#
if [[ ($cmd != execluma) && ($cmd != exesx9) && ($cmd != cleancluma) && ($cmd != cleansx9) ]]; then
  umacho
  echo "COSMORUN : Runs COSMO, cleans working and output directories (on automatically detected host)."
  echo
  echo "SYNTAX :"
  echo
  echo "lmrun_uc clean                  cleans working and output directories"
  echo
  echo "lmrun_uc exe                    starts COSMO"
  echo
  echo "lmrun_uc cleancluma, execluma   explicitly sets cluma as host"
  echo
  echo "lmrun_uc cleansx9, exesx9       explicitly sets sx9 as host"
  echo
  echo "lmrun_uc                        displays help text"
  echo
  exit
fi
#
#################################################
# generate output directory
#################################################
#
if [ ! -d $OUTPUT ] ; then
  mkdir -p $OUTPUT
fi
#
echo "VK CONFIG with DATE        ${INIT_D}.${INIT_M}.${INIT_Y} ${INIT_H}:00"
echo "VK CONFIG with CONV.SCHEME $CONV_SCHEME"
echo "VK CONFIG with INPUTDIR    $INIDIR"
echo "VK CONFIG with WORKDIR     $workdir"
echo "VK CONFIG with OUTPUTDIR   $OUTPUT"
echo "VK CONFIG with JOBNAME     $jobname"
#
#################################################
# clean up only
#################################################
#
if [[ ($cmd = cleancluma) || ($cmd = cleansx9) ]]; then
  echo "tidy up ..."
  cd $workdir
  rm -f cosmo_de_job
  rm ftrace.out.*
  rm mon.out.*
  rm -f *~
  rm -f YU*
  rm -f INPUT_*
  rm -f ${jobname}*
  rm -f output/*
  rm -f $OUTPUT/*
  rm -f cosmo_de_job
  rm -f M_*
  rm -f diag*
  exit 0
fi
#
#################################################
# start COSMO
#################################################
#
if [[ ($cmd = execluma) || ($cmd = exesx9) ]]; then
rm -f cosmo_de_job
echo "generate cosmo_de_job ..."

cat >> cosmo_de_job << namelists
#################################################
# namelist settings
#################################################

#################################################
# cat together the INPUT*-files
#################################################

cat > INPUT_ORG << end_input_org
 &LMGRID
  startlat_tot  = -0.10,  startlon_tot  =  -2.949,
  pollat=40.0,        pollon=-170.0,
  dlon=0.010,         dlat=0.010,
  ie_tot=ie_tot_bldsva,         je_tot=je_tot_bldsva,          ke_tot=50,
 /
 &RUNCTL
  hstart = 0.0,   nstop = $nsteps,    dt      = dt_cos_bldsva,    ydate_ini='$DATUM',
  nprocx = $NPX,  nprocy = $NPY,   nprocio = $NPIO,
  lphys      = .TRUE.,   luse_rttov    = .FALSE.,  luseobs = .FALSE., leps = .FALSE.,
  lreorder   = .FALSE.,  lreproduce    = .TRUE.,   itype_timing = 0,
  ldatatypes = .TRUE.,   ltime_barrier = .TRUE.,  ncomm_type=3,
  nboundlines= 4, idbg_level=2, ldump_ascii=.TRUE., lartif_data=.FALSE., 
  ldiagnos   = .TRUE., lperi_x=.FALSE., lperi_y=.FALSE.,
 /
 &TUNING
  clc_diag  =   0.5,
  pat_len   = 500.0,
  tur_len   = 150.0,
  rlam_heat =   1.0,
  rlam_mom  =   0.0,
  rat_lam   =   1.0,
  rat_can   =   1.0,
  rat_sea   =  20.0,
  c_lnd     =   2.0,
  c_soil    =   1.0,
  c_sea     =   1.5,
  z0m_dia   =   0.2,
  crsmin    = 150.0,
  wichfakt  =   0.0,
  qc0       =   0.0002,
  q_crit    =   1.6,
  mu_rain   =   0.5,
  rain_n0_factor = 0.1,
  v0snow    =    20,
  tkhmin    =   0.4,
  tkmmin    =   0.4,
 /
end_input_org

cat > INPUT_SAT  << end_input_sat
 &SATCTL
  itype_rttov=10,
  num_sensors=1,
  sat_input_01='MSG'     ,2,'SEVIRI',8, .TRUE., .TRUE., .TRUE., .TRUE.,
  nchan_input_01=1,2,3,4,5,6,7,8
  lcon_clw=.TRUE.,
 /
end_input_sat

cat > INPUT_IO  << end_input_io
 &IOCTL
  lasync_io=.FALSE, ngribout=1,
  yform_read='grb1',
 /
 &DATABASE
 /
 &GRIBIN
  lan_t_so0=.TRUE., lan_t_cl=.TRUE., lan_w_cl=.TRUE., lan_vio3=.TRUE.,
  lan_hmo3=.TRUE., lan_plcov=.TRUE., lan_lai=.TRUE., lan_rootdp=.TRUE.,
  lan_t_snow=.TRUE., lan_w_i=.TRUE., lan_w_snow=.TRUE., lan_rho_snow=.TRUE.,
  lan_w_so=.TRUE.,
  hincbound=1.0,
  lchkini    = .TRUE.,  lchkbd    = .TRUE.,  lbdana=.FALSE.,
! lchkini    = .FALSE.,  lchkbd    = .FALSE.,  lbdana=.FALSE.,
  lana_qi    = .TRUE.,  llb_qi    = .TRUE.,  lana_rho_snow=.FALSE., 
  lana_qr_qs = .TRUE.,  llb_qr_qs = .TRUE.,
  lana_qg    = .FALSE.,  llb_qg    = .FALSE.,
  ydirini='$INIDIR',
  ydirbd='$BD_DIR',
 /
 &GRIBOUT
    ncomb=0,$nsteps,360,
    luvmasspoint=.true.,
    lanalysis=.FALSE.,
    lcheck=.TRUE.,
    lwrite_const=.TRUE.,
    l_fi_filter=.TRUE.,
    nunit_of_time=1,
    yform_write='ncdf',
    ydir='$OUTPUT',
    yvarml='U         ','V         ','W         ','T         ',
           'P         ','QV        ','QC        ','QI        ',
           'QR        ','QS        ','QG        ','Q_SEDIM   ',
           'CLC       ','TKE       ','TKVM      ','TKVH      ',
           'T_G       ','QV_S      ','PS        ','TOT_PREC  ',
           'ASOB_S    ','ATHB_S    ','ASHFL_S   ','ALHFL_S   ',
           'AUMFL_S   ','AVMFL_S   ','TCM       ','TCH       ',
           'TG        ',
 /
end_input_io

cat > INPUT_DYN << end_input_dyn
 &DYNCTL
    l2tls=.TRUE., lcond=.TRUE., ldyn_bbc=.FALSE., ldiabf_lh=.TRUE.,
    l_diff_Smag=.TRUE., y_scalar_advect='BOTT2_STRANG', 
    lspubc=.TRUE.,
    itype_hdiff=2, hd_dhmax=250.,
    hd_corr_trcr_bd=0.0, hd_corr_t_bd=0.75, hd_corr_u_bd=0.75, hd_corr_p_bd=0.75,
    hd_corr_trcr_in=0.0, hd_corr_t_in=0.0,  hd_corr_u_in=0.1,  hd_corr_p_in=0.0,
    irunge_kutta=1, irk_order=3, iadv_order=5, itype_fast_waves=2,
    itype_bbc_w=114,
    nrdtau=5, xkd=0.1,
    rlwidth=20000.0, itype_outflow_qrsg=2,
 /
end_input_dyn

cat > INPUT_PHY << end_input_phy
 &PHYCTL
    lgsp=.TRUE.,
      itype_gscp=4,
      lsuper_coolw=.TRUE.,
    lrad=.TRUE.,
      nradcoarse=1,
      lradf_avg=.FALSE.
      hincrad=0.25,
      lforest=.TRUE.,
      itype_albedo=1,
    ltur=.TRUE.,
      ninctura=1,
      lexpcor=.FALSE.,
      ltmpcor=.FALSE.,
      lprfcor=.FALSE.,
      lnonloc=.FALSE.,
      lcpfluc=.FALSE.,
      limpltkediff=.TRUE.,
      itype_turb=3,
      imode_turb=1,
      itype_tran=2,
      imode_tran=1,
      itype_wcld=2,
      icldm_rad =4,
      icldm_turb=2,
      icldm_tran=0,
      itype_synd=2,
    lsoil=.TRUE.,
      itype_evsl=2,
      itype_trvg=2,
      lmulti_layer=.TRUE.,
      lmelt=.TRUE.,
      lmelt_var=.TRUE.,
      ke_soil = 7,
      czml_soil = 0.005, 0.02, 0.06, 0.18, 0.54, 1.62, 4.86, 14.58,
    lconv=.TRUE.,
      lcape=.FALSE.,
      lconf_avg=.TRUE.,
      lconv_inst=.TRUE.,
      itype_conv=3,
      nincconv=10,
    llake=.FALSE.,
    lseaice=.FALSE.,
    lsso=.FALSE.,
      ltkesso=.FALSE.,
 /
end_input_phy

cat > INPUT_DIA << end_input_dia
 &DIACTL
  itype_diag_gusts=4,
  n0meanval=0, nincmeanval=1,
  lgplong=.TRUE., lgpshort=.FALSE., lgpspec=.FALSE.,
  n0gp=0,      hincgp=0.25,
  stationlist_tot= 0, 0, 50.050,  8.600, 'Frankfurt-Flughafen',
                   0, 0, 52.220, 14.135, 'Lindenberg_Obs',
                   0, 0, 52.167, 14.124, 'Falkenberg',
                   0, 0, 52.182, 13.954, 'Waldstation_Kehrigk',
                   0, 0, 47.800, 10.900, 'Hohenpeissenberg',
                   0, 0, 50.783,  6.100, 'Aachen',
                   0, 0, 48.433, 10.933, 'Augsburg',
                   0, 0, 49.980, 11.682, 'Bayreuth',
                   0, 0, 52.300, 10.450, 'Braunschweig',
                   0, 0, 51.967,  4.933, 'Cabauw',
                   0, 0, 50.283, 10.983, 'Coburg',
                   0, 0, 47.419, 10.982, 'Schneefernerhaus',
                   0, 0, 49.920,  7.960, 'Geisenheim',
                   0, 0, 53.633,  9.983, 'Hamburg',
                   0, 0, 54.750, 17.533, 'Leba',
                   0, 0, 51.200, 16.200, 'Legnica',
                   0, 0, 53.780, 21.580, 'Mikolajki',
                   0, 0, 37.122, -5.579, 'Moron_la_Frontera',
                   0, 0, 53.779,  8.669, 'Nordholz',
                   0, 0, 48.067, 11.267, 'Oberpfaffenhofen',
                   0, 0, 57.425, 18.983, 'Oestergarsholm',
                   0, 0, 46.817,  6.935, 'Payerne',
                   0, 0, 53.133, 16.750, 'Pila',
                   0, 0, 52.383, 13.067, 'Potsdam',
                   0, 0, 54.533,  9.550, 'Schleswig',
                   0, 0, 48.833,  9.200, 'Stuttgart',
                   0, 0, 51.350, 19.870, 'Sulejow',
                   0, 0, 63.086, 25.980, 'Viitasaari',
                   0, 0, 54.633, 25.100, 'Vilnius',
                   0, 0, 52.167, 20.967, 'Warschau',
                   0, 0, 48.400, 11.700, 'Weihenstephan',
                   0, 0, 51.217, 18.567, 'Wielund',
                   0, 0, 51.550, 23.530, 'Wlodawa',
                   0, 0, 53.311, 11.838, 'Ziegendorf',
 /
end_input_dia


cat > INPUT_EPS << end_input_eps
 &EPSCTL
  iepsmem=0, iepstyp=55, iepstot=15,
 /
end_input_eps

cat > INPUT_ASS << end_input_ass
 &NUDGING
  lnudge  =.true.,
  ycdfdir='$OBSDIR/',
  hnudgsta= 0.0,  hnudgend = 4.0,  tconbox = 180.0,
  lverif  =.true.,
  llhn    =.true., llhnverif=.true., lhn_wweight=.true.,
  yform_lansfc='api1',
  rqrsgmax= 0.4,
  radar_in='$RADARI/',  
  nradar  = 34,
  itype_obfile = 2,
  hversta = 0.001, hverend = 4.0,
  khumbal = 100,
  mruntyp = 2,
  ntpscor = 1,  ptpstop=400.0,  luvgcor=.TRUE.,
  ltipol  =.TRUE.,  tipolmx = 3.0,  wtukrsa = 3.0,  wtukrse = 1.0,
  ltipsu  =.TRUE.,  tipmxsu = 1.0,  wtuksua = 1.5,  wtuksue = 0.5,
  mveripr = 2,
                                    wtukara = 1.5,  wtukare = 0.5,
  msprpar = 1,  msprpsu = 0,
  gnudg   = 0.0006, 0.0012, 0.0006, 0.0006,
  gnudgsu = 0.0006, 0.0012, 0.0000, 0.0006,
  gnudgar = .0006, .0000, .0006, .0000,
  vcorls  = .333 , .333 , .04  , .04  ,  vcutof  = 0.75, 0.75, 1.0 , 1.0 ,
  vcorlsu = .013 , .013 , .002 ,.00001,  vcutosu = 0.75, 0.75, 4.0 ,0.001,
  vcsnisu = 2500., 2500., 9.   , 9.   ,
                                         rhvfac  = 1.0 , 0.0 , 0.83, 0.83,
  rhinfl  =    0.,   70.,    0.,    0.,  rhtfac  = 1.3 , 1.43, 1.3 , 1.3 ,
  rhiflsu =   70.,   70.,  100.,   70.,  rhtfsu  = 1.0 , 1.43, 1.0 , 1.0 ,
  fnondiv = 0.8  ,   cnondiv = 0.1    ,  cutofr  = 3.5 , 3.5 , 3.5 , 3.5 ,
  tnondiv = 1.1  ,                       cutofsu = 2.0 , 3.5 , 2.0 , 2.0 ,
  topobs  =  849., 1099.,  799.,  699.,
  botmod  = 1099., 1099., 1099.,  899.,
  lscadj  =.TRUE.,.TRUE.,.TRUE.,.FALSE.,
  dtqc    =  720.,                       qcvf    = 5.00, 1.00,10.00, 1.00,
  qcc     =  0.00,500.00,  0.00,  0.00,
  qccsu   =   12.,  500.,   12.,    .7,
  mqcorr92= 2,
  lsynop  =.true.,
  laircf  =.true.,
  ldribu  =.true.,
  ltemp   =.true.,
  lpilot  =.true.,
  lcd132  =.true., lcd133=.false., lcd136=.false.,
  maxmlo  = 1600,  maxsgo = 5000,  maxuso = 5000,  nolbc = 5,
  altopsu =  100., 5000., 5000., 5000.,  thairh  = 20.,
  exnlat  = 90.,  exslat =-90.,  exwlon = -180.,  exelon = 180.,
  lsurfa  =.true., 
  lt2m    =.true.,    ht2a = 0.,  ht2i = 1.,
  lrh2m   =.true.,   hh2a = 0.,  hh2i = 1.,
  lprecp  =.true.,  hprc = 0.,  raintp = 12.,
  lff10m  =.true.,  hffa = 0.,  hffi = 1.,
  lpraof  =.false.,  lprodr =.true. ,  ldiasa =.true.,  noctrq = 9,
  dinlat  = 55.,  dislat = 45.,  diwlon =  7.,  dielon = 14.,
  ionl    =167,   jonl =103,     ionl2 =167,    jonl2 =103,
  lff10m  =.true., hffa=0., hffi=1.,
 /
end_input_ass

cat > INPUT_IDEAL << end_input_artifctl
 &ARTIFCTL
    ldebug_artif = .true., 
      idbg_artif_level = 5
    irefatm = 2,
      p0sl = 1e5,       ! reference surface (z = 0.0 m) pressure [Pa]
      t0sl = 300.0,     ! reference surface temperature [K]
      dt0lp = 42.0,     ! logarithmic temperature gradient [K]
      delta_t = 75.0,   ! temperature diff. surface - stratosphere [K]
      h_scal = 10000.0, ! e-folding height of exponential adjustment to the stratosphere temp. [m]
      bvref = 0.01,     ! constant Brund-Vaisala-frequency for irefatm=3 [1/s]
    ivctype=2,
      zspacing_type = 'galchen',! sub-type of coordinate spec.
      exp_galchen = 2.6,        ! exponent in the Gal-Chen formula
      vcflat = 11000.0,         ! height, above which coordinate levels become flat [m]
      zz_top = 23000.0,         ! height of model top, if it has to be specified explicitly [m]
    linit_realoro=.false.,
    href_oro=0.0,
    itype_topo = 0,
    lnosurffluxes_m = .false.,   !tcm=0, true, free-slipe BC
    lnosurffluxes_h = .false.,   !tch=0, true
    itype_soil_c = 1, 
      z0_c      = 0.01,        ! z_0 in m
      fr_land_c = 1.0,         ! land fraction, dimensionless
      soiltyp_c = 3.0,         ! soiltype, dimensionless
      plcov_c   = 0.6,         ! plant cover, dimensionless
      lai_c     = 3.0,         ! LAI, dimensionless
      rootdp_c  = 0.7,         ! root depth in m
      for_e_c   = 0.2,         ! area fraction of evergreen forests
      for_d_c   = 0.2,         ! area fraction of decidious forests
      h_ice_c   = 0.1,         ! ice thickness in m
      t_ice_c   = 270.0,       ! T at the snow-ice or air-ice interf. in K
   itype_soil_tw = 1, 
      t_soil_c  = -1.0,     ! t_soil in K (if <0, t_s is taken instead)
      wf_soil_c = 0.3,      ! soil water saturation, dimensionless (0 ... 1)
      t_snow_c  = -1.0,     ! t_snow in K (if <0, t_s is taken instead)
      w_snow_c  = 0.0,      ! snow water equivalent in m H2O
      w_i_c     = 0.0,      ! interception storage on plants in m H2O
   itype_artifprofiles = 2,
   itype_anaprof_tqv = 2,
   itype_anaprof_uv = 3,
     nlayers_poly = 4,
     p_base_poly = 1e5,
     h_poly = 0.0,1500.0,5000.0,13000.0,
     t_poly = 300.0, 292.5, 275.0, 235.0,
     tgr_poly = 5.0e-3, 5.0e-3,5.0e-3,-1.0e-4, 
     rh_poly = 0.5, 0.5,0.1,2.0e-2,
     rhgr_poly = 0.0, 1.15e-4, 1.0e-5,0.0,

     u_infty = 0.5,
/
end_input_artifctl

namelists

#################################################
# cleanup
#################################################

rm -f INPUT_ORG INPUT_IO INPUT_DYN INPUT_DIA INPUT_PHY INPUT_INI
rm -f INPUT_ASS INPUT_SAT INPUT_EPS

chmod u+x cosmo_de_job
fi
./cosmo_de_job
exit 0
