#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download
#
# DART $Id: mkmf_dart_to_model Wed Apr 11 20:26:43 CEST 2018 $

../../../../mkmf/mkmf -p dart_to_parflow -t ../../../../mkmf/mkmf.template   \
 -a "../../../.." path_names_dart_to_parflow

exit $status
