#!/bin/tcsh
#2018-07-24_SBr
#USAGE="source $0"
#for bld and work w/ TerrSysMP on JUWELS
#for standard user

module --force purge

# Only necessary if modules are missing after maintenence
module load Intel/2018.2.199-GCC-5.5.0
module load ParaStationMPI/5.2.1-1


# basic toolchain, latest Intel compilers and ParaStation MPI

# libs for TerrSysMP
module load Tcl/8.6.8
module load Hypre/2.14.0
module load Silo/4.10.2
#grib1 dwd
module load netCDF/4.6.1
module load netCDF-Fortran/4.4.4
module load parallel-netcdf/1.9.0


# standard analysis and vis. libs and tools 
module load NCO/4.7.4
module load NCL/6.4.0
module load CDO/1.9.3
#module load ncview/2.1.5
module load Python/2.7.14
#module load matplotlib/1.3.1-Python-2.7.9
module load netcdf4-python/1.4.0-Python-2.7.14
module load SciPy-Stack/2018a-Python-2.7.14
module load basemap/1.0.7-Python-2.7.14
module load h5py/2.7.1-Python-2.7.14
module load petsc4py/3.9.0-Python-3.6.5
module load mpi4py/3.0.0-Python-2.7.14
#image magick / feh ... some standard viewer is missing

module li
