#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download
#
# DART $Id: mkmf_perfect_model_obs Wed Apr 11 20:26:43 CEST 2018 $

../../../../mkmf/mkmf -p perfect_model_obs -t ../../../../mkmf/mkmf.template \
 -a "../../../.." path_names_perfect_model_obs

exit $status
