#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download
#
# DART $Id: mkmf_create_fixed_network_seq Wed Apr 11 20:26:43 CEST 2018 $

../../../../mkmf/mkmf -p create_fixed_network_seq -t ../../../../mkmf/mkmf.template \
 -a "../../../.." path_names_create_fixed_network_seq

exit $status
