#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download
#
# DART $Id: mkmf_fill_inflation_restart Wed Apr 11 20:26:43 CEST 2018 $

../../../../mkmf/mkmf -p fill_inflation_restart -t ../../../../mkmf/mkmf.template   \
 -a "../../../.." path_names_fill_inflation_restart

exit $status
